---
apiVersion: v1
kind: Secret
metadata:
  name: skraft-redhat-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/skraft-redhat-new-backend-gitops
